<?php

declare (strict_types=1);
namespace Php_Stan\Extension_Installer;

use function array_key_exists;
use function array_keys;
use function class_exists;
use Composer\Composer;
use Composer\Event_Dispatcher\Event_Subscriber_Interface;
use Composer\IO\Io_Interface;
use Composer\Plugin\Plugin_Interface;
use Composer\Script\Event;
use Composer\Script\Script_Events;
use Composer\Semver\Constraint\Constraint_Interface;
use Composer\Semver\Constraint\Multi_Constraint;
use Composer\Semver\Intervals;
use Composer\Util\Filesystem;
use function count;
use const DIRECTORY_SEPARATOR;
use function dirname;
use function file_exists;
use function file_put_contents;
use function getcwd;
use function in_array;
use function is_file;
use function ksort;
use function md5;
use function md5_file;
use function sort;
use function sprintf;
use function strpos;
use function var_export;
final class Plugin implements Plugin_Interface, Event_Subscriber_Interface
{
    private static string $generated_file_template = <<<'PHP_WRAP'
    <?php declare(strict_types = 1);
    
    namespace PHPStan\ExtensionInstaller;
    
    /**
     * This class is generated by phpstan/extension-installer.
     * @internal
     */
    final class GeneratedConfig
    {
    
    	public const EXTENSIONS = %s;
    
    	public const NOT_INSTALLED = %s;
    
    	/** @var string|null */
    	public const PHPSTAN_VERSION_CONSTRAINT = %s;
    
    	private function __construct()
    	{
    	}
    
    }
    
    PHP_WRAP;
    public function activate(Composer $composer, Io_Interface $io): void
    {
        // noop
    }
    public function deactivate(Composer $composer, Io_Interface $io): void
    {
        // noop
    }
    public function uninstall(Composer $composer, Io_Interface $io): void
    {
        // noop
    }
    /**
     * @return array<string, string>
     */
    public static function get_subscribed_events(): array
    {
        return [Script_Events::POST_INSTALL_CMD => 'process', Script_Events::POST_UPDATE_CMD => 'process'];
    }
    public function process(Event $event): void
    {
        $io = $event->get_io();
        if (!file_exists(__DIR__)) {
            $io->write('<info>phpstan/extension-installer:</info> Package not found (probably scheduled for removal); extensions installation skipped.');
            return;
        }
        $composer = $event->get_composer();
        $installation_manager = $composer->get_installation_manager();
        $generated_config_file_path = __DIR__ . '/GeneratedConfig.php';
        $old_generated_config_file_hash = null;
        if (is_file($generated_config_file_path)) {
            $old_generated_config_file_hash = md5_file($generated_config_file_path);
        }
        $not_installed_packages = [];
        $installed_packages = [];
        $ignored_packages = [];
        $data = [];
        $fs = new Filesystem();
        $ignore = [];
        $package_extra = $composer->get_package()->get_extra();
        if (isset($package_extra['phpstan/extension-installer']['ignore'])) {
            $ignore = $package_extra['phpstan/extension-installer']['ignore'];
        }
        $phpstan_version_constraints = [];
        foreach ($composer->get_repository_manager()->get_local_repository()->get_packages() as $package) {
            if ($package->get_type() !== 'phpstan-extension' && !isset($package->get_extra()['phpstan'])) {
                if (strpos($package->get_name(), 'phpstan') !== false && !in_array($package->get_name(), ['phpstan/phpstan', 'phpstan/phpstan-shim', 'phpstan/phpdoc-parser', 'phpstan/extension-installer'], true)) {
                    $not_installed_packages[$package->get_name()] = $package->get_full_pretty_version();
                }
                continue;
            }
            if (in_array($package->get_name(), $ignore, true)) {
                $ignored_packages[] = $package->get_name();
                continue;
            }
            $install_path = $installation_manager->get_install_path($package);
            if ($install_path === null) {
                continue;
            }
            $cwd = getcwd();
            $absolute_install_path = $fs->is_absolute_path($install_path) ? $install_path : ($cwd !== false ? $cwd : '') . DIRECTORY_SEPARATOR . $install_path;
            $package_requires = $package->get_requires();
            $phpstan_constraint = null;
            if (array_key_exists('phpstan/phpstan', $package_requires)) {
                $phpstan_constraint = $package_requires['phpstan/phpstan']->get_constraint();
                if ($phpstan_constraint->get_lower_bound()->is_zero()) {
                    continue;
                }
                if ($phpstan_constraint->get_upper_bound()->is_positive_infinity()) {
                    continue;
                }
                $phpstan_version_constraints[] = $phpstan_constraint;
            }
            $data[$package->get_name()] = ['install_path' => $absolute_install_path, 'relative_install_path' => $fs->find_shortest_path(dirname($generated_config_file_path), $absolute_install_path, true), 'extra' => $package->get_extra()['phpstan'] ?? null, 'version' => $package->get_full_pretty_version(), 'phpstanVersionConstraint' => $phpstan_constraint !== null ? $this->constraint_into_string($phpstan_constraint) : null];
            $installed_packages[$package->get_name()] = true;
        }
        $phpstan_version_constraint = null;
        if (count($phpstan_version_constraints) > 0 && class_exists(Intervals::class)) {
            if (count($phpstan_version_constraints) === 1) {
                $multi_constraint = $phpstan_version_constraints[0];
            } else {
                $multi_constraint = new Multi_Constraint($phpstan_version_constraints);
            }
            $phpstan_version_constraint = $this->constraint_into_string(Intervals::compact_constraint($multi_constraint));
        }
        ksort($data);
        ksort($installed_packages);
        ksort($not_installed_packages);
        sort($ignored_packages);
        $generated_config_file_contents = sprintf(self::$generated_file_template, var_export($data, true), var_export($not_installed_packages, true), var_export($phpstan_version_constraint, true));
        file_put_contents($generated_config_file_path, $generated_config_file_contents);
        $io->write('<info>phpstan/extension-installer:</info> Extensions installed');
        if ($old_generated_config_file_hash === md5($generated_config_file_contents)) {
            return;
        }
        foreach (array_keys($installed_packages) as $name) {
            $io->write(sprintf('> <info>%s:</info> installed', $name));
        }
        foreach (array_keys($not_installed_packages) as $name) {
            $io->write(sprintf('> <comment>%s:</comment> not supported', $name));
        }
        foreach ($ignored_packages as $name) {
            $io->write(sprintf('> <comment>%s:</comment> ignored', $name));
        }
    }
    private function constraint_into_string(Constraint_Interface $constraint): string
    {
        return sprintf('%s%s, %s%s', $constraint->get_lower_bound()->is_inclusive() ? '>=' : '>', $constraint->get_lower_bound()->get_version(), $constraint->get_upper_bound()->is_inclusive() ? '<=' : '<', $constraint->get_upper_bound()->get_version());
    }
}